name: 'Delta TypeScript Graph'
auther: 'ysk8hori'
description: 'Visualizes changes in typescript-file dependencies.'
inputs:
  access-token:
    description: 'Access token for the repo'
    required: false
    default: ${{ github.token }}
  tsconfig-root:
    description: '(Deprecated: Use tsconfig instead.) Specifies the root directory where tsconfig will be searched.'
    required: false
    default: './'
  tsconfig:
    description: 'Specifies the path to the tsconfig file.'
    required: false
  max-size:
    description: 'Maximum number of nodes to display in the graph when there are many change files'
    required: false
    default: '30'
  orientation:
    description: 'Orientation of the graph (TB or LR)'
    required: false
    default: 'TB'
  debug:
    description: 'Enable debug mode'
    required: false
    default: false
  in-details:
    description: 'Whether to wrap Mermaid in a `<details>` tag for collapsing'
    required: false
    default: false
  exclude:
    description: 'Array of files to exclude'
    required: false
    default: 'node_modules' # node_modules をデフォルトの除外リストに追加
  include-index-file-dependencies:
    description: 'Whether to display dependencies of index.ts files that refer to the change target files'
    required: false
    default: false
  comment-title:
    description: 'Specifies the title of the comment posted on the PR.'
    required: false
    default: 'Delta TypeScript Graph'
  show-metrics:
    description: 'Calculate and display metrics for the graph'
    required: false
    default: false
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'git-pull-request'
  color: 'blue'
