on: pull_request

# Sets permissions of the GITHUB_TOKEN to allow write pull-requests
permissions:
  pull-requests: write

jobs:
  delta-typescript-graph-job:
    runs-on: ubuntu-latest
    name: Test dummy project
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Delta Typescript Graph
        id: tsg
        uses: ysk8hori/delta-typescript-graph-action@f7280ec67f94b084e1b79d071cf8e472cc3266fb
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
          tsconfig: './dummy_project/tsconfig-dummy.json'
          max-size: 100
          orientation: LR
          debug: true
          include-index-file-dependencies: true
          comment-title: 'Dummy project dependency graph'
