on: pull_request

# Sets permissions of the GITHUB_TOKEN to allow write pull-requests
permissions:
  pull-requests: write

jobs:
  delta-typescript-graph-job:
    runs-on: ubuntu-latest
    name: Test dummy project
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Delta Typescript Graph
        id: tsg
        uses: ysk8hori/delta-typescript-graph-action@c1df77ddef12545351cc9af560bf923c65c7c093
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
          tsconfig: './dummy_project/tsconfig-dummy.json'
          max-size: 100
          orientation: LR
          debug: true
          include-index-file-dependencies: true
          comment-title: 'Dummy project dependency graph'
          show-metrics: true
